=== Gayathri2109/Training_exercise/bill.dtd
<!ELEMENT bill (customername,billno,billdate,item+)>
<!ELEMENT customername (#PCDATA)>
<!ELEMENT billno (#PCDATA)>
<!ELEMENT billdate (#PCDATA)>
<!ELEMENT item (sno,itemname,unit,price,quantity,totalamt)>
<!ELEMENT sno (#PCDATA)>
<!ELEMENT itemname (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT totalamt (#PCDATA)>

=== Gayathri2109/Training_exercise/bill.xml
<!DOCTYPE books SYSTEM "bill.dtd">
<bill>
	<customername>Gayathri</customername>
	<billno>452367</billno>
	<billdate>12.03.2021</billdate>
	<item>
		<sno>1</sno>
		<itemname>Daal</itemname>
		<unit>1</unit>
		<price>60</price>
		<quantity>2</quantity>
		<totalamt>120</totalamt>
	</item>
	<item>
		<sno>2</sno>
		<itemname>Rice</itemname>
		<unit>1</unit>
		<price>70</price>
		<quantity>2</quantity>
		<totalamt>140</totalamt>
	</item>	
</bill>
